namespace SpriteKind {
    export const decoration = SpriteKind.create()
    export const chest = SpriteKind.create()
    export const comerciante = SpriteKind.create()
    export const portal = SpriteKind.create()
    export const material = SpriteKind.create()
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    nena,
    assets.animation`nena-animation-up`,
    500,
    false
    )
    direccionNena = 0
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    nena,
    assets.animation`nena-animation-right`,
    500,
    false
    )
    direccionNena = 2
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    nena,
    assets.animation`nena-animation-left`,
    500,
    false
    )
    direccionNena = 1
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (direccionNena == 1) {
        animation.runImageAnimation(
        nena,
        [img`
            ..............ffffff....
            .............f2feeeeff..
            ............f222feeeeff.
            .......cc...feeeeffeeef.
            .......cdc.fe2222eeffff.
            .......cddcf2effff222ef.
            ........cddcffeeefffffff
            .........cddce44fbe44eff
            ..........cdceddf14d4eef
            ..........cccdeddd4eeef.
            ...........edd4e44eeff..
            ............ee442222f...
            .............f2e2222f...
            .............f554444f...
            ..............ffffff....
            ................fff.....
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ..............fff.......
            .............f2fffff....
            ...........ff22eeeeeff..
            ..........ff222eeeeeeff.
            ..........feeeefffeeeef.
            .........fe2222eeefffff.
            .........f2efffff222efff
            ..cc.....fffeeefffffffff
            ..cdcc...fee44fbbe44efef
            ..ccddcc..feddfbb4d4eef.
            ....cdddceefddddd4eeef..
            .....ccdcddee2222222f...
            ......cccdd44e544444f...
            .........eeeeffffffff...
            .............ff...fff...
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ..............ffffff....
            .............f2feeeeff..
            ............f222feeeeff.
            ............feeeeffeeef.
            ...........fe2222eeffff.
            ...........f2effff222ef.
            ...........fffeeefffffff
            ...........fee44fbe44eff
            ............feddf14d4eef
            .............fdddd4eeef.
            .............fe444eddf..
            .............ccc22eddf..
            .............cdc22fee...
            ............cddc4444f...
            ...........cddcfffff....
            ..........cddc..fff.....
            ..........cdc...........
            ..........cc............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (direccionNena == 0) {
        animation.runImageAnimation(
        nena,
        [img`
            ........................
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff..........
            .ffefbf44fbfeff.........
            .fee41fddf14eef.........
            fdfeeddddd4eff..........
            fbffee444edd4e..........
            fbf4f2222edde...........
            fcf.f22cccee............
            .ff.f44cdc4f............
            ....fffddcff............
            .....fddcff.............
            ....cddc................
            ....cdc.................
            ....cc..................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `,img`
            ......ffff..............
            ....fff22fff............
            ...fff2222fff...........
            ..fffeeeeeefff..........
            ..ffe222222eef..........
            ..fe2ffffff2ef..........
            ..ffffeeeeffff......ccc.
            .ffefbf44fbfeff....cddc.
            .ffefbf44fbfeff...cddc..
            .fee4dddddd4eef.ccddc...
            fdfeeddddd4eeffecddc....
            fbffee4444ee4fddccc.....
            fbf4f222222f1edde.......
            fcf.f222222f44ee........
            .ff.f445544f............
            ....ffffffff............
            .....ff..ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (direccionNena == 2) {
        animation.runImageAnimation(
        nena,
        [img`
            ........................
            ....ffffff..............
            ..ffeeeef2f.............
            .ffeeeef222f............
            .feeeffeeeef...cc.......
            .ffffee2222ef.cdc.......
            .fe222ffffe2fcddc.......
            fffffffeeeffcddc........
            ffe44ebf44ecddc.........
            fee4d41fddecdc..........
            .feee4dddedccc..........
            ..ffee44e4dde...........
            ...f222244ee............
            ...f2222e2f.............
            ...f444455f.............
            ....ffffff..............
            .....fff................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            .......fff..............
            ....fffff2f.............
            ..ffeeeee22ff...........
            .ffeeeeee222ff..........
            .feeeefffeeeef..........
            .fffffeee2222ef.........
            fffe222fffffe2f.........
            fffffffffeeefff.....cc..
            fefe44ebbf44eef...ccdc..
            .fee4d4bbfddef..ccddcc..
            ..feee4dddddfeecdddc....
            ...f2222222eeddcdcc.....
            ...f444445e44ddccc......
            ...ffffffffeeee.........
            ...fff...ff.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ....ffffff..............
            ..ffeeeef2f.............
            .ffeeeef222f............
            .feeeffeeeef............
            .ffffee2222ef...........
            .fe222ffffe2f...........
            fffffffeeefff...........
            ffe44ebf44eef...........
            fee4d41fddef............
            .feee4ddddf.............
            ..fdde444ef.............
            ..fdde22ccc.............
            ...eef22cdc.............
            ...f4444cddc............
            ....fffffcddc...........
            .....fff..cddc..........
            ...........cdc..........
            ............cc..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    }
    if (esArbol == 1) {
        if (nena.overlapsWith(arbol)) {
            golpesArbol += 1
            if (golpesArbol == 3) {
                sprites.destroy(arbol)
                tronco1 = sprites.create(assets.image`miImagen13`, SpriteKind.material)
                tiles.placeOnTile(tronco1, tiles.getTileLocation(6, 6))
                esArbol = 0
                golpesArbol = 0
                reapareceArbol1 = game.runtime() + 5000
            }
        }
    }
    if (esArbol2 == 1) {
        if (nena.overlapsWith(arbol2)) {
            golpesArbol2 += 1
            if (golpesArbol2 == 3) {
                sprites.destroy(arbol2)
                tronco2 = sprites.create(assets.image`miImagen13`, SpriteKind.material)
                tiles.placeOnTile(tronco2, tiles.getTileLocation(8, 7))
                esArbol2 = 0
                golpesArbol2 = 0
                reapareceArbol2 = game.runtime() + 5000
            }
        }
    }
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    nena,
    assets.animation`nena-animation-down`,
    500,
    false
    )
})
let tronco2: Sprite = null
let tronco1: Sprite = null
let arbol2: Sprite = null
let arbol: Sprite = null
let nena: Sprite = null
let esArbol2 = 0
let golpesArbol2 = 0
let esArbol = 0
let golpesArbol = 0
let direccionNena = 0
let reapareceArbol2 = 0
let reapareceArbol1 = 0
reapareceArbol1 = 0
reapareceArbol2 = 0
direccionNena = 0
golpesArbol = 0
esArbol = 1
golpesArbol2 = 0
esArbol2 = 1
scene.setBackgroundImage(assets.image`background`)
tiles.setCurrentTilemap(tilemap`nivel7`)
nena = sprites.create(assets.image`nena-front`, SpriteKind.Player)
controller.moveSprite(nena, 100, 100)
nena.setStayInScreen(true)
tiles.placeOnTile(nena, tiles.getTileLocation(4, 5))
let trader = sprites.create(assets.image`comerciante`, SpriteKind.comerciante)
tiles.placeOnTile(trader, tiles.getTileLocation(1, 5))
arbol = sprites.create(assets.image`árbol`, SpriteKind.material)
tiles.placeOnTile(arbol, tiles.getTileLocation(6, 5))
arbol2 = sprites.create(assets.image`árbol`, SpriteKind.material)
tiles.placeOnTile(arbol2, tiles.getTileLocation(8, 6))
game.onUpdateInterval(500, function () {
    if (esArbol == 0 && game.runtime() > reapareceArbol1) {
        sprites.destroy(tronco1)
        arbol = sprites.create(assets.image`árbol`, SpriteKind.material)
        tiles.placeOnTile(arbol, tiles.getTileLocation(6, 5))
        esArbol = 1
    }
})
game.onUpdateInterval(500, function () {
    if (esArbol2 == 0 && game.runtime() > reapareceArbol2) {
        sprites.destroy(tronco2)
        arbol2 = sprites.create(assets.image`árbol`, SpriteKind.material)
        tiles.placeOnTile(arbol2, tiles.getTileLocation(8, 6))
        esArbol2 = 1
    }
})
