@namespace
class SpriteKind:
    decoration = SpriteKind.create()
    chest = SpriteKind.create()
    comerciante = SpriteKind.create()
    portal = SpriteKind.create()
    material = SpriteKind.create()

def on_down_pressed():
    global direccionNena
    animation.run_image_animation(nena,
        assets.animation("""
            nena-animation-up
            """),
        500,
        False)
    direccionNena = 0
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

def on_right_pressed():
    global direccionNena
    animation.run_image_animation(nena,
        assets.animation("""
            nena-animation-right
            """),
        500,
        False)
    direccionNena = 2
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_left_pressed():
    global direccionNena
    animation.run_image_animation(nena,
        assets.animation("""
            nena-animation-left
            """),
        500,
        False)
    direccionNena = 1
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_a_pressed():
    global golpesArbol, tronco1, esArbol, arbol, golpesArbol2, tronco2, esArbol2, arbol2
    if direccionNena == 1:
        animation.run_image_animation(nena,
            [img("""
                    ..............ffffff....
                    .............f2feeeeff..
                    ............f222feeeeff.
                    .......cc...feeeeffeeef.
                    .......cdc.fe2222eeffff.
                    .......cddcf2effff222ef.
                    ........cddcffeeefffffff
                    .........cddce44fbe44eff
                    ..........cdceddf14d4eef
                    ..........cccdeddd4eeef.
                    ...........edd4e44eeff..
                    ............ee442222f...
                    .............f2e2222f...
                    .............f554444f...
                    ..............ffffff....
                    ................fff.....
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """),
                img("""
                    ........................
                    ..............fff.......
                    .............f2fffff....
                    ...........ff22eeeeeff..
                    ..........ff222eeeeeeff.
                    ..........feeeefffeeeef.
                    .........fe2222eeefffff.
                    .........f2efffff222efff
                    ..cc.....fffeeefffffffff
                    ..cdcc...fee44fbbe44efef
                    ..ccddcc..feddfbb4d4eef.
                    ....cdddceefddddd4eeef..
                    .....ccdcddee2222222f...
                    ......cccdd44e544444f...
                    .........eeeeffffffff...
                    .............ff...fff...
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """),
                img("""
                    ..............ffffff....
                    .............f2feeeeff..
                    ............f222feeeeff.
                    ............feeeeffeeef.
                    ...........fe2222eeffff.
                    ...........f2effff222ef.
                    ...........fffeeefffffff
                    ...........fee44fbe44eff
                    ............feddf14d4eef
                    .............fdddd4eeef.
                    .............fe444eddf..
                    .............ccc22eddf..
                    .............cdc22fee...
                    ............cddc4444f...
                    ...........cddcfffff....
                    ..........cddc..fff.....
                    ..........cdc...........
                    ..........cc............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """)],
            100,
            False)
    if direccionNena == 0:
        animation.run_image_animation(nena,
            [img("""
                    ........................
                    ......ffff..............
                    ....fff22fff............
                    ...fff2222fff...........
                    ..fffeeeeeefff..........
                    ..ffe222222eef..........
                    ..fe2ffffff2ef..........
                    ..ffffeeeeffff..........
                    .ffefbf44fbfeff.........
                    .fee41fddf14eef.........
                    fdfeeddddd4eff..........
                    fbffee444edd4e..........
                    fbf4f2222edde...........
                    fcf.f22cccee............
                    .ff.f44cdc4f............
                    ....fffddcff............
                    .....fddcff.............
                    ....cddc................
                    ....cdc.................
                    ....cc..................
                    ........................
                    ........................
                    ........................
                    ........................
                    """),
                img("""
                    ........................
                    ........................
                    .......ff...............
                    .....ff22ff.............
                    ...fff2222fff...........
                    ..fff222222fff..........
                    ..fff222222fff..........
                    ..feeeeeeeeeeff.........
                    .ffe22222222eff.........
                    .fffffeeeefffff.........
                    fdfefbf44fbfeff.........
                    fbfe41fddf14ef..........
                    fbffe4dddd4efe..........
                    fcfef22222f4e...........
                    .ff4f44554f4e...........
                    ....ffffffdde...........
                    .....ffffedde...........
                    ..........ee............
                    .........ccc............
                    ........cc1cc...........
                    .........c1c............
                    .........c1c............
                    .........c1c............
                    .........c1c............
                    """),
                img("""
                    ......ffff..............
                    ....fff22fff............
                    ...fff2222fff...........
                    ..fffeeeeeefff..........
                    ..ffe222222eef..........
                    ..fe2ffffff2ef..........
                    ..ffffeeeeffff......ccc.
                    .ffefbf44fbfeff....cddc.
                    .ffefbf44fbfeff...cddc..
                    .fee4dddddd4eef.ccddc...
                    fdfeeddddd4eeffecddc....
                    fbffee4444ee4fddccc.....
                    fbf4f222222f1edde.......
                    fcf.f222222f44ee........
                    .ff.f445544f............
                    ....ffffffff............
                    .....ff..ff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """)],
            100,
            False)
    if direccionNena == 2:
        animation.run_image_animation(nena,
            [img("""
                    ........................
                    ....ffffff..............
                    ..ffeeeef2f.............
                    .ffeeeef222f............
                    .feeeffeeeef...cc.......
                    .ffffee2222ef.cdc.......
                    .fe222ffffe2fcddc.......
                    fffffffeeeffcddc........
                    ffe44ebf44ecddc.........
                    fee4d41fddecdc..........
                    .feee4dddedccc..........
                    ..ffee44e4dde...........
                    ...f222244ee............
                    ...f2222e2f.............
                    ...f444455f.............
                    ....ffffff..............
                    .....fff................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """),
                img("""
                    ........................
                    .......fff..............
                    ....fffff2f.............
                    ..ffeeeee22ff...........
                    .ffeeeeee222ff..........
                    .feeeefffeeeef..........
                    .fffffeee2222ef.........
                    fffe222fffffe2f.........
                    fffffffffeeefff.....cc..
                    fefe44ebbf44eef...ccdc..
                    .fee4d4bbfddef..ccddcc..
                    ..feee4dddddfeecdddc....
                    ...f2222222eeddcdcc.....
                    ...f444445e44ddccc......
                    ...ffffffffeeee.........
                    ...fff...ff.............
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """),
                img("""
                    ....ffffff..............
                    ..ffeeeef2f.............
                    .ffeeeef222f............
                    .feeeffeeeef............
                    .ffffee2222ef...........
                    .fe222ffffe2f...........
                    fffffffeeefff...........
                    ffe44ebf44eef...........
                    fee4d41fddef............
                    .feee4ddddf.............
                    ..fdde444ef.............
                    ..fdde22ccc.............
                    ...eef22cdc.............
                    ...f4444cddc............
                    ....fffffcddc...........
                    .....fff..cddc..........
                    ...........cdc..........
                    ............cc..........
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    ........................
                    """)],
            100,
            False)
    if esArbol == 1:
        if nena.overlaps_with(arbol):
            golpesArbol += 1
            if golpesArbol == 3:
                sprites.destroy(arbol)
                tronco1 = sprites.create(assets.image("""
                        miImagen13
                        """),
                    SpriteKind.material)
                tiles.place_on_tile(tronco1, tiles.get_tile_location(6, 6))
                arbol.set_image(assets.image("""
                    miImagen13
                    """))
                esArbol = 0
                golpesArbol = 0
                pause(5000)
                sprites.destroy(tronco1)
                arbol = sprites.create(assets.image("""
                    árbol
                    """), SpriteKind.material)
                tiles.place_on_tile(arbol, tiles.get_tile_location(6, 5))
                esArbol = 1
    if esArbol2 == 1:
        if nena.overlaps_with(arbol2):
            golpesArbol2 += 1
            if golpesArbol2 == 3:
                sprites.destroy(arbol2)
                tronco2 = sprites.create(assets.image("""
                        miImagen13
                        """),
                    SpriteKind.material)
                tiles.place_on_tile(tronco2, tiles.get_tile_location(8, 7))
                arbol2.set_image(assets.image("""
                    miImagen13
                    """))
                esArbol2 = 0
                golpesArbol2 = 0
                pause(5000)
                sprites.destroy(tronco2)
                arbol2 = sprites.create(assets.image("""
                    árbol
                    """), SpriteKind.material)
                tiles.place_on_tile(arbol2, tiles.get_tile_location(8, 6))
                esArbol2 = 1
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_up_pressed():
    animation.run_image_animation(nena,
        assets.animation("""
            nena-animation-down
            """),
        500,
        False)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

tronco2: Sprite = None
tronco1: Sprite = None
arbol2: Sprite = None
arbol: Sprite = None
nena: Sprite = None
esArbol2 = 0
golpesArbol2 = 0
esArbol = 0
golpesArbol = 0
direccionNena = 0
direccionNena = 0
golpesArbol = 0
esArbol = 1
golpesArbol2 = 0
esArbol2 = 1
scene.set_background_image(assets.image("""
    background
    """))
tiles.set_current_tilemap(tilemap("""
    nivel7
    """))
nena = sprites.create(assets.image("""
    nena-front
    """), SpriteKind.player)
controller.move_sprite(nena, 100, 100)
nena.set_stay_in_screen(True)
tiles.place_on_tile(nena, tiles.get_tile_location(4, 5))
trader = sprites.create(assets.image("""
        comerciante
        """),
    SpriteKind.comerciante)
tiles.place_on_tile(trader, tiles.get_tile_location(1, 5))
arbol = sprites.create(assets.image("""
    árbol
    """), SpriteKind.material)
tiles.place_on_tile(arbol, tiles.get_tile_location(6, 5))
arbol2 = sprites.create(assets.image("""
    árbol
    """), SpriteKind.material)
tiles.place_on_tile(arbol2, tiles.get_tile_location(8, 6))